### PR TITLE
feat(tracing): using tracing instead of log

### PR DESCRIPTION
**Pull request by gabrik**
Sister of: https://github.com/eclipse-zenoh/zenoh/pull/895

### CODE REVIEW

**Comment by gabrik** [comment]
@DariusIMP can you please have a look?

**Comment by gabrik** [comment]
Same as zenoh-java, based on main but it does not build.

**Comment by DariusIMP** [comment]
PR #69 solves the building problem.

**Comment by gabrik** [comment]
> PR #69 solves the building problem.

I'll wait it to be merged and rebase this

**Pull request merged**
